export const ADD_USER_PROJECT = 'ADD_USER_PROJECT'
export const DEL_USER_PROJECT = 'DEL_USER_PROJECT'
export const DEL_ALL_USER_PROJECT = 'DEL_ALL_USER_PROJECT'

export const ADD_KEYWORD_PROJECT = 'ADD_KEYWORD_PROJECT'
export const DEL_KEYWORD_PROJECT = 'DEL_KEYWORD_PROJECT'
export const DEL_ALL_KEYWORD_PROJECT = 'DEL_ALL_KEYWORD_PROJECT'

export const ADD_REPOST_PROJECT = 'ADD_REPOST_PROJECT'
export const DEL_REPOST_PROJECT = 'DEL_REPOST_PROJECT'
export const DEL_ALL_REPOST_PROJECT = 'DEL_ALL_REPOST_PROJECT'

export const ADD_COMMENT_PROJECT = 'ADD_COMMENT_PROJECT'
export const DEL_COMMENT_PROJECT = 'DEL_COMMENT_PROJECT'
export const DEL_ALL_COMMENT_PROJECT = 'DEL_ALL_COMMENT_PROJECT'

export const ADD_WECHATPUBLIC_PROJECT = 'ADD_WECHATPUBLIC_PROJECT'
export const DEL_WECHATPUBLIC_PROJECT = 'DEL_WECHATPUBLIC_PROJECT'
export const DEL_ALL_WECHATPUBLIC_PROJECT = 'DEL_ALL_WECHATPUBLIC_PROJECT'

export const SET_SCRAPY = 'SET_SCRAPY'
