export const ADD_USER_PROJECT = 'ADD_USER_PROJECT'
export const ADD_KEYWORD_PROJECT = 'ADD_KEYWORD_PROJECT'
export const ADD_REPOST_PROJECT = 'ADD_REPOST_PROJECT'
export const ADD_COMMENT_PROJECT = 'ADD_COMMENT_PROJECT'
